### ISSUE TITLE
GTFS differences

### ISSUE THREAD

**Issue by splendidbits** [flibbertigibbet/patco-gtfs#19]
"The official GTFS differs from the one produced by this project. I intend to continue maintaining this project for awhile yet."

Could you explain some of those differences? :-)

**Comment by flibbertigibbet** [comment]
The GTFS here has a `shapes.txt`, which is missing from the official one. I have stopped updating this GTFS project, and should update the README.

**Comment by splendidbits** [comment]
Gotcha. How did you generate the shapes.txt? By joining the lat/longs in stop_times.txt?

Thanks for your work on this. I'm sure others appreciated it.

**Comment by flibbertigibbet** [comment]
Thanks for your interest! In the `shapes` folder are the scripts and files I used to fetch the path from OpenStreetMap data and produce the `shapes.txt`.

**Comment by flibbertigibbet** [comment]
A benefit of having the `shapes.txt` is that GTFS-reading programs can know the actual path the line takes instead of interpolating between the stops. Interpolating the stops results in a linestring that goes sailing across the Delaware somewhere south of the Franklin bridge.

**Comment by splendidbits** [comment]
Yep, aware of shapes (upgrading septa-instant to use proper shapes now).

Thanks again for all of this. I did check out that folder after I wrote the question. Probably should have done it before - very clever of you for stringing that together.
